<?php

namespace App\Form;

use App\Entity\AuditSearch;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\ResetType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AuditSearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('audittitle', TextType::class,[
				'required' => false,
				'label' => false,
				'attr' => [
					'placeholder' => 'Audit Title'
				]
			])
//			->add('auditstandard', TextType::class,[
//				'required' => false,
//				'label' => false,
//				'attr' => [
//					'placeholder' => 'Audit Standard'
//				]
//			])
			->add('auditstandard', ChoiceType::class, [
				'label' => false,
				'choices' => [
					'' => '',
					'Qualikita' => 'Qualikita',
					'FAMI-QS' => 'FAMI-QS',
					'FSSC V3' => 'FSSC V3',
				]])

//			->add('reset', ResetType::class, [
//				'attr' => ['class' => 'save']
//			])
//            ->add('Submit', SubmitType::class, [
//            	'label' => 'Search'
//			])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AuditSearch::class,
			'method'=>'get',
			'csrf_protection' => false
        ]);
    }

    public  function getBlockPrefix()
	{
		return ''; // TODO: Change the autogenerated stub
	}
}
